name: main-npm
on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'src/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: 'main'
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'

    - name: Install Dependencies
      run: |
        yarn --frozen-lockfile

    - uses:  'phips28/gh-action-bump-version@master'
      name:  'Automated Version Bump'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PACKAGEJSON_DIR:  '.'
      with:
        commit-message: 'CI: bumps version to {{version}} [skip ci]'

    - name: Run npm build
      env:
        CI: false
      run: yarn build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: package.json