concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
    paths:
      - '!src/ui/**'
      - '!package.json'
      - 'src/stories/**'
      - '.github/workflows/main-storybook.yml'

jobs:
  storybook:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Run storybook build
      env:
        CI: false
      run: |
        pnpm run build-storybook

    - name: Deploy storybook gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs
        force_orphan: true

    - name: notify analytica of build
      if: always()
      uses: andreigecanalytica/analytica.click.gh@v2
      with:
        ANALYTICA_TOKEN: '${{ secrets.ANALYTICATOKEN }}'
