name: main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'src/**'
      - '!src/story'
      - '!src/story/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 6
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Run storybook build
      env:
        CI: false
      run: npm run build-storybook

    - uses:  'phips28/gh-action-bump-version@master'
      name:  'Automated Version Bump'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PACKAGEJSON_DIR:  '.'
      with:
        commit-message: 'CI: bumps version to {{version}} [skip ci]'

    - name: Run npm build
      env:
        CI: false
      run: npm run build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: package.json

    - name: Deploy storybook gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs