name: main-npm
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'src/story/**'
      - '.github/workflows/storybook.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'yarn'

    - name: Install Dependencies
      run: |
        yarn --frozen-lockfile

    - name: Run storybook build
      env:
        CI: false
      run: yarn build-storybook

    - name: Deploy storybook gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs